server:
  port: ${PORT:0}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PruebaDB
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
  profiles:
    active:
    - local 
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
